apiVersion: v1
kind: Secret

metadata:
  name: sqlserver-secret
  namespace: ecommerce

type: Opaque

stringData:

  MSSQL_SA_PASSWORD: "YourStrong@Pass123"
  ConnectionStrings__ASPNETCoreD11: "Server=sqlserver;Database=ASPNET_API_EcommerceAPI;User Id=sa;Password=YourStrong@Pass123;TrustServerCertificate=True;MultipleActiveResultSets=True"