apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: sql-pvc
  namespace: ecommerce 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ecommerce-sql-sc 
  resources:
    requests:
      storage: 10Gi

